### ISSUE TITLE
Identifying the projects to be studied

### ISSUE THREAD

**Issue by coco-lab-2022** [CocoLab-2022/signalsongithub#5]
As the other one, we may random select 200 from the 2000 most starred projects.

**Comment by coco-lab-2022** [comment]
Does it still blocks our progress?

**Comment by jiangzheng77** [comment]
I randomly selected 200 numbers like this.
![image](https://user-images.githubusercontent.com/47706313/167615431-ba99e35b-e9bd-407d-b5b9-54ae5700072a.png)
