### ISSUE TITLE
To do 1: Identify the developers and if they use activity overview

### ISSUE THREAD

**Issue by coco-lab-2022** [CocoLab-2022/signalsongithub#6]
Let's suppose the 200 (or 100) projects has been randomly sampled from Yisi Han's 2000 project list, then we need to:

- Identify the developers of the 200 (or 100) projects. How to? You can use GitHub API: [https://docs.github.com/en/rest/repos/repos#list-repository-contributors];
- Since one may contribute to multiple projects, you need to clean the lists a little bit;
- This may be a long list, don't worry, we may set some thresholds on no. of contributions to filter some of them out (for example, those who make limited contributions or do not use pull request for a while);
- Then, we have to do some manual work----we need to check if those people use the activity overview feature (of course, this can be automated by building a classifier, using one's profile page as the input, but you still need to manually label the training and testing data);
- then, we have a pair of lists, one contains developers use activity overview, and one consists of non-users;

Simple enough, right?

**Comment by jiangzheng77** [comment]
Got it.

**Comment by weiwang310** [comment]
Clearly

**Comment by coco-lab-2022** [comment]
I finished collecting all contributors of the selected 200 projects. Will develop a method to determine the adoption of activity overview later.

Indeed, it is fairly easy. I noticed if someone enables activity overview, their profile page would contain something like that:
<button type="submit" name="user[activity_overview_enabled]" value="0" class="dropdown-item ws-normal btn-link text-left pl-5" role="menuitem">

HTML parser such as beautifulsoup would do it elegantly. I will finish it by the end of tmr.

**Comment by coco-lab-2022** [comment]
Some update:
Indeed, there are 34,157 unique developers involved in these 200 projects. Now I have a concern that some of them may not do enough pull-requests. So I decided before checking their adoption of activity-overview, I need to learn the distribution of their pulls. I am basically done with it today. I will try to have some updates by tmr night.

**Comment by coco-lab-2022** [comment]
Some update:
Eventually I got all 34,000ish ppl's contribution counts. I will make some analysis and post them here.
And I am still targeting to start observations on June 1st (which is pretty doable according to the current status).

**Comment by coco-lab-2022** [comment]
@jiangzheng77 @weiwang310 @19991010wan 
Okay, let's say:
If setting 100 as the threshold, there are 2577 individual developers,
If setting 120 (~10 per month), there are 2149 developers.

However, I noticed there are some bots who did a lot of prs. 
According to my recently-accepted paper: "From Specialized Mechanics to Project Butlers: the Usage of Bots in OSS Development," there is no reliable way ready to automatically determine if an account is a bot or a person.

I suspect we may still need a manual work to look at every account (each of us may have to check ~800 account). Let me think it a little bit tomorrow.

Any thoughts are welcome.

**Comment by coco-lab-2022** [comment]
Closed as 2022/06/02
